name: Cache specific base images

on: [push]

jobs:
  test-on-something:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker images
        run: docker images -a

      - name: Cache Node.js Docker image
        id: cache-node
        uses: actions/cache@v3
        with:
          path: /tmp/docker-cache
          key: node-18-image-${{ runner.os }}

      - name: Load cached Node.js image
        if: steps.cache-node.outputs.cache-hit == 'true'
        run: |
          if [ -f /tmp/docker-cache/node-18.tar ]; then
            docker load -i /tmp/docker-cache/node-18.tar
          fi

      - name: Pull Node.js image
        run: |
          if ! docker image inspect node:18 >/dev/null 2>&1; then
            docker pull node:18
            mkdir -p /tmp/docker-cache
            docker save -o /tmp/docker-cache/node-18.tar node:18
          fi
      
      - name: List all caches (via GitHub API)
        env:
          GITHUB_TOKEN: ${{ secrets.BLUEPRINT_GITHUB_TEST }}
        run: |
          sleep 5
          curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/caches?key=node-18-image"

      - name: Check docker images
        run: docker images -a
