name: CI Demo

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 虚拟机
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Say Hello
        run: echo "Hello, World!"
